language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: eduarte
  api_key:
    secure: 0tx4TSKMXHu/W1TR7Q4gZDFTUvPGCakuN2d1MkUVK1tNkA8oBGBexAkf7yZVPPgLlX1PT6TxlDcCNpvr2HJpf/z5U1Kj8GrPb5VX74x/nCuhwbOYJfa6cV9YRonVvfZD1vKjelBaoE2jnlBCxwFnjetzAs/8arVqiIlf7yRg1HvJmTQ8iFOlXkEjKxjYvnENikzgZQU3J+B2P8QFUEoFCAlxItCGS3Uwhcvk7S1BqjorCpSe2h3tHxpkt4L8EMVacsXiLKv/+JohHCYBwoDpYdsFUuLkSJXugic+HTWm8z1edobdF6F0z4ve24wGwMiYrXSFQsYw4Dsl2MMcnKn2OF5JqLUmSp3jwhXnAmb6j0P1TwcAgo6JF1IfdM0BcbNTwhH+aK5U2Xv1OMD3ZaHz7C9kB5HAbNz/M1bwX/I9oNMoojxw9BWJfewFQU00Kkbmpi10vA8k/OZsiJoYcau1pkaS2GNJgvwMuQLS6B6YesvCH8fNg/KwaKRG/0behHcm0SmZh/7U0yeDrXtvpnzxNtPKGDUNJof68h3+DcnmlPVKtUrAIpDyP27JtMgcgOTl1M0gESays7n6f/2KP7uyU/Z1zUl2j6E3D1VWQz4K1SPs+FQwuS6rQ5Jp+CGjM2Dcn3U47txVn6785kJF6TKrQmetq3Ymp8RYf7wGUTBt1Eg=
